package by.urban.web_project.controller.concrete;

public enum CommandName {
    DO_AUTH,
    DO_REGISTRATION,
    GO_TO_REGISTRATION_PAGE,
    GO_TO_AUTHENTIFICATION_PAGE,
    WRITE_ADMIN,
    GO_TO_INDEX_PAGE,
    GO_TO_NEWS_PAGE,
    SHOW_ALL_NEWS,
    GO_TO_USER_ACCOUNT_PAGE,
    GO_TO_AUTHOR_ACCOUNT_PAGE,
    GO_TO_CHANGE_FORM,
    GO_TO_ADD_NEWS_FORM_PAGE,
    ADD_NEWS,
    CHANGE_NAME,
    CHANGE_PASSWORD,
    CHANGE_BIO,
    CHANGE_NEWS_ARTICLE,
    SHOW_STUB_PAGE,
    NO_SUCH_COMMAND,
    LOGOUT
}
