package by.urban.web_project.bean;

import java.util.ArrayList;
import java.util.List;

public class NewsDatabase {
	// делаем заглушки для новостей вместо метода для вытягивания новостей из БД
	private static List<News> news = new ArrayList<>();
	// breaking - самый высокий приоритет, центрируется
	// top - приоритет средний, центрируется, если появляется breaking, то
	// перемещается в верхний левый угол
	// regular - низкий приоритет, располагаются по бокам
	static {
		news.add(new News(1, NewsImportance.BREAKING, "Заглушка breaking заголовка 1", "images/breakingNewsImg.jpg",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolorsit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"));
		news.add(new News(2, NewsImportance.REGULAR, "Заглушка заголовка 1", "images/regularNewsImg.jpg",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"
						+ "Sed maximus metus ipsum, quis tempor urna lacinia non. Morbi faucibus mattis ornare. Cras vulputate ligula id magna semper, non dictum nunc dictum. Maecenas consectetur imperdiet odio. Proin sem sapien, tristique id augue vel, ornare faucibus mi. Sed lobortis lectus euismod mattis condimentum. Curabitur eget sapien porta, tristique leo non, volutpat elit. Vivamus vel tellus non justo lacinia commodo. Vestibulum ornare lacinia aliquam. In id augue maximus quam hendrerit convallis a sed velit."));
		news.add(new News(3, NewsImportance.REGULAR, "Заглушка заголовка 2", "images/regularNewsImg.jpg",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"
						+ "Sed maximus metus ipsum, quis tempor urna lacinia non. Morbi faucibus mattis ornare. Cras vulputate ligula id magna semper, non dictum nunc dictum. Maecenas consectetur imperdiet odio. Proin sem sapien, tristique id augue vel, ornare faucibus mi. Sed lobortis lectus euismod mattis condimentum. Curabitur eget sapien porta, tristique leo non, volutpat elit. Vivamus vel tellus non justo lacinia commodo. Vestibulum ornare lacinia aliquam. In id augue maximus quam hendrerit convallis a sed velit."));
		news.add(new News(4, NewsImportance.TOP, "Заглушка top заголовка 1", "images/topNewsImg.png",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"
						+ "Sed maximus metus ipsum, quis tempor urna lacinia non. Morbi faucibus mattis ornare. Cras vulputate ligula id magna semper, non dictum nunc dictum. Maecenas consectetur imperdiet odio. Proin sem sapien, tristique id augue vel, ornare faucibus mi. Sed lobortis lectus euismod mattis condimentum. Curabitur eget sapien porta, tristique leo non, volutpat elit. Vivamus vel tellus non justo lacinia commodo. Vestibulum ornare lacinia aliquam. In id augue maximus quam hendrerit convallis a sed velit."));
		news.add(new News(5, NewsImportance.REGULAR, "Заглушка заголовка 3", "images/regularNewsImg.jpg",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"
						+ "Sed maximus metus ipsum, quis tempor urna lacinia non. Morbi faucibus mattis ornare. Cras vulputate ligula id magna semper, non dictum nunc dictum. Maecenas consectetur imperdiet odio. Proin sem sapien, tristique id augue vel, ornare faucibus mi. Sed lobortis lectus euismod mattis condimentum. Curabitur eget sapien porta, tristique leo non, volutpat elit. Vivamus vel tellus non justo lacinia commodo. Vestibulum ornare lacinia aliquam. In id augue maximus quam hendrerit convallis a sed velit."));
		news.add(new News(6, NewsImportance.REGULAR, "Заглушка заголовка 4", "images/regularNewsImg.jpg",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"
						+ "Sed maximus metus ipsum, quis tempor urna lacinia non. Morbi faucibus mattis ornare. Cras vulputate ligula id magna semper, non dictum nunc dictum. Maecenas consectetur imperdiet odio. Proin sem sapien, tristique id augue vel, ornare faucibus mi. Sed lobortis lectus euismod mattis condimentum. Curabitur eget sapien porta, tristique leo non, volutpat elit. Vivamus vel tellus non justo lacinia commodo. Vestibulum ornare lacinia aliquam. In id augue maximus quam hendrerit convallis a sed velit."));
		news.add(new News(7, NewsImportance.BREAKING, "Заглушка breaking заголовка 2", "images/breakingNewsImg.jpg",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"
						+ "Sed maximus metus ipsum, quis tempor urna lacinia non. Morbi faucibus mattis ornare. Cras vulputate ligula id magna semper, non dictum nunc dictum. Maecenas consectetur imperdiet odio. Proin sem sapien, tristique id augue vel, ornare faucibus mi. Sed lobortis lectus euismod mattis condimentum. Curabitur eget sapien porta, tristique leo non, volutpat elit. Vivamus vel tellus non justo lacinia commodo. Vestibulum ornare lacinia aliquam. In id augue maximus quam hendrerit convallis a sed velit."));
		news.add(new News(8, NewsImportance.TOP, "Заглушка top заголовка 2", "images/topNewsImg.png",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"
						+ "Sed maximus metus ipsum, quis tempor urna lacinia non. Morbi faucibus mattis ornare. Cras vulputate ligula id magna semper, non dictum nunc dictum. Maecenas consectetur imperdiet odio. Proin sem sapien, tristique id augue vel, ornare faucibus mi. Sed lobortis lectus euismod mattis condimentum. Curabitur eget sapien porta, tristique leo non, volutpat elit. Vivamus vel tellus non justo lacinia commodo. Vestibulum ornare lacinia aliquam. In id augue maximus quam hendrerit convallis a sed velit."));
		news.add(new News(9, NewsImportance.REGULAR, "Заглушка заголовка 5", "images/regularNewsImg.jpg",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"
						+ "Sed maximus metus ipsum, quis tempor urna lacinia non. Morbi faucibus mattis ornare. Cras vulputate ligula id magna semper, non dictum nunc dictum. Maecenas consectetur imperdiet odio. Proin sem sapien, tristique id augue vel, ornare faucibus mi. Sed lobortis lectus euismod mattis condimentum. Curabitur eget sapien porta, tristique leo non, volutpat elit. Vivamus vel tellus non justo lacinia commodo. Vestibulum ornare lacinia aliquam. In id augue maximus quam hendrerit convallis a sed velit."));
		news.add(new News(10, NewsImportance.REGULAR, "Заглушка заголовка 6", "images/regularNewsImg.jpg",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"
						+ "Sed maximus metus ipsum, quis tempor urna lacinia non. Morbi faucibus mattis ornare. Cras vulputate ligula id magna semper, non dictum nunc dictum. Maecenas consectetur imperdiet odio. Proin sem sapien, tristique id augue vel, ornare faucibus mi. Sed lobortis lectus euismod mattis condimentum. Curabitur eget sapien porta, tristique leo non, volutpat elit. Vivamus vel tellus non justo lacinia commodo. Vestibulum ornare lacinia aliquam. In id augue maximus quam hendrerit convallis a sed velit."));
		news.add(new News(11, NewsImportance.REGULAR, "Заглушка заголовка 7", "images/regularNewsImg.jpg",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"
						+ "Sed maximus metus ipsum, quis tempor urna lacinia non. Morbi faucibus mattis ornare. Cras vulputate ligula id magna semper, non dictum nunc dictum. Maecenas consectetur imperdiet odio. Proin sem sapien, tristique id augue vel, ornare faucibus mi. Sed lobortis lectus euismod mattis condimentum. Curabitur eget sapien porta, tristique leo non, volutpat elit. Vivamus vel tellus non justo lacinia commodo. Vestibulum ornare lacinia aliquam. In id augue maximus quam hendrerit convallis a sed velit."));
		news.add(new News(12, NewsImportance.REGULAR, "Заглушка заголовка 8", "images/regularNewsImg.jpg",
				"Съешь же ещё этих мягких французских булок, да выпей чаю. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper lacus eget massa efficitur, id porta sapien lobortis. Morbi semper magna ac sapien interdum tincidunt. Nunc nec nisi massa. Ut varius ornare erat ac elementum. Nam accumsan ante eget lectus interdum luctus et sit amet velit. Nullam condimentum luctus tortor nec lacinia. Quisque non felis gravida, sodales nisi ut, tincidunt nibh. Nam mauris urna, semper et diam sit amet, laoreet posuere libero. Sed massa felis, bibendum non porttitor et, fermentum quis nisi. Vestibulum vel justo lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet nulla faucibus, mattis augue quis, porta justo. Ut massa ex, porta in finibus vel, congue non velit. Pellentesque viverra in ligula eget imperdiet. Donec ornare commodo lobortis.\r\n"
						+ "\r\n"
						+ "Aenean porttitor semper odio, a pretium tellus dapibus quis. Praesent rhoncus lectus quis urna placerat vestibulum. Nulla pretium sit amet tortor vel iaculis. Praesent ornare nec enim vulputate euismod. Praesent volutpat sagittis sem, quis congue justo venenatis ut. Donec vitae risus ipsum. Aliquam auctor scelerisque velit volutpat consequat. Phasellus luctus tellus a pulvinar interdum. Praesent ullamcorper fermentum libero sed consequat. Sed diam lectus, hendrerit sed malesuada quis, lobortis a elit. Vivamus in purus nec ligula semper egestas. Nulla molestie, justo tincidunt faucibus ullamcorper, tellus augue pulvinar mauris, ut dignissim leo eros ac turpis. Nam aliquet, purus dictum sollicitudin mollis, leo nisi accumsan mi, nec euismod nibh mi eu lectus. Fusce placerat tincidunt ipsum, ac malesuada neque semper vitae. Maecenas commodo facilisis nunc, a posuere nulla congue vel. Integer massa quam, viverra ac quam ac, sodales porta purus.\r\n"
						+ "\r\n"
						+ "In venenatis tristique neque quis accumsan. Quisque commodo efficitur elit, id consequat odio varius quis. Phasellus vel neque eget lectus sagittis consequat eget vitae arcu. Phasellus auctor vestibulum dolor, sed tincidunt leo congue hendrerit. Ut feugiat sem non nulla accumsan, suscipit fermentum nunc porta. Aliquam porttitor egestas enim ac imperdiet. Maecenas malesuada, felis et consectetur commodo, orci nisi vulputate est, in semper ante elit eu tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n"
						+ "\r\n"
						+ "Morbi a dolor est. Integer urna tortor, volutpat vel vestibulum vel, pulvinar sit amet magna. Donec non tempor lorem. Cras tempor tortor erat, eu viverra purus vulputate sit amet. Etiam facilisis a justo at sollicitudin. Quisque tristique interdum ante at ultrices. Phasellus finibus turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n"
						+ "\r\n"
						+ "Aliquam ligula magna, fringilla vitae efficitur sit amet, vulputate a magna. In ligula leo, lobortis id ullamcorper a, condimentum non nibh. Vestibulum venenatis lobortis nisi id tincidunt. Sed vehicula a ante nec mollis. Integer faucibus hendrerit consequat. Vestibulum dictum pellentesque arcu, vitae condimentum ligula convallis vel. Mauris ornare ante nibh, quis faucibus nibh hendrerit vitae. Nam dapibus neque ligula, nec gravida turpis ultrices ut. Pellentesque enim eros, semper congue augue vitae, mollis lobortis nisl. Phasellus sed nisi vitae turpis venenatis semper sit amet non lectus. Mauris vehicula dui eget dolor pharetra vulputate. Sed malesuada dui in ipsum maximus sodales. Integer rhoncus ut ligula vel viverra.\r\n"
						+ "\r\n"
						+ "Mauris velit erat, semper sed semper nec, interdum non diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec arcu diam, hendrerit eget augue at, hendrerit posuere est. Ut molestie arcu a ipsum rutrum volutpat. Ut accumsan vehicula ipsum, sit amet luctus nibh elementum ut. Duis eu leo sagittis, volutpat mauris eu, luctus urna. Nam rhoncus ac leo posuere faucibus. Donec ac aliquet augue. Etiam fermentum imperdiet quam eget auctor. Etiam et sem quis quam rutrum eleifend et id mi. Nulla convallis quam nec mollis aliquet. Integer maximus dui erat, sit amet condimentum massa dapibus id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis nunc nec mi tincidunt, eget bibendum leo elementum. Morbi vestibulum fringilla tortor, quis pharetra ligula tincidunt sit amet. Etiam vitae metus porttitor, rutrum ex ac, elementum nibh.\r\n"
						+ "\r\n"
						+ "Nullam in tincidunt urna. Curabitur aliquam, nunc a lobortis viverra, arcu nunc rutrum enim, quis auctor tortor lectus ut mi. Nulla ut ipsum est. Praesent vitae rhoncus nibh. Sed a sodales enim. In eu enim nunc. Proin vestibulum dignissim metus, in laoreet tortor varius ac. Mauris bibendum risus felis, nec porttitor augue maximus a. Nullam egestas sit amet leo id placerat. Nulla rutrum tincidunt fermentum. Donec sed accumsan ex. Integer vestibulum ligula vel sagittis rutrum.\r\n"
						+ "\r\n"
						+ "Sed nec justo vel quam tempus volutpat in in quam. Proin ac magna lacinia, consectetur enim eu, euismod ante. Aliquam vel augue sapien. Phasellus malesuada, mi vel rutrum viverra, neque dolor tincidunt arcu, at bibendum justo metus at dui. Nunc euismod efficitur orci malesuada commodo. Praesent rutrum non mauris a accumsan. Curabitur vehicula nulla vel neque iaculis porttitor. Ut ultrices, ligula in tincidunt sollicitudin, nulla ex condimentum neque, at ullamcorper lectus turpis tristique nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae metus odio. Vestibulum eleifend magna massa, id pretium felis viverra et. In magna massa, hendrerit vel malesuada nec, convallis egestas felis. Praesent laoreet, risus nec gravida interdum, ligula purus sagittis massa, ut tempus augue magna posuere risus. Duis rutrum ligula quis dui cursus, sed efficitur mauris bibendum.\r\n"
						+ "\r\n"
						+ "Phasellus ornare faucibus iaculis. Fusce sapien felis, mattis vel condimentum a, ullamcorper quis dui. Nulla at lectus erat. Sed lobortis felis vel nulla porttitor varius. Nulla ut vulputate urna, in porta erat. Pellentesque in eros at orci cursus ullamcorper at id justo. Donec vitae varius enim. Aenean laoreet ornare ligula, eget rutrum mi lacinia consectetur. Nulla augue leo, varius at nunc in, semper volutpat neque. Cras et tincidunt risus. Suspendisse potenti. Sed varius sem arcu. Sed scelerisque sed dolor sed tincidunt. Duis accumsan, magna ut tincidunt auctor, est metus mattis mi, sit amet sagittis magna velit facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat.\r\n"
						+ "\r\n"
						+ "Sed maximus metus ipsum, quis tempor urna lacinia non. Morbi faucibus mattis ornare. Cras vulputate ligula id magna semper, non dictum nunc dictum. Maecenas consectetur imperdiet odio. Proin sem sapien, tristique id augue vel, ornare faucibus mi. Sed lobortis lectus euismod mattis condimentum. Curabitur eget sapien porta, tristique leo non, volutpat elit. Vivamus vel tellus non justo lacinia commodo. Vestibulum ornare lacinia aliquam. In id augue maximus quam hendrerit convallis a sed velit."));
	}

	// метод будет использоваться для передачи в общий список с новостями
	public static List<News> getAllNews() {
		return new ArrayList<>(news);
	}

	// метод будет использоваться для отображения новости на отдельной странице
	public static News getNewsById(int id) {
		for (News item : news) {
			if (item.getId() == id) {
				return item;
			}
		}
		return null;
	}
}
